### ISSUE TITLE
Rime installed many schemas without activiting them.

### ISSUE THREAD

**Issue by shifujun** [fcitx/flatpak-fcitx5#22]
In install config it install many schemas:
https://github.com/fcitx/flatpak-fcitx5/blob/5bcc68e095581f75df7bc938a45f4019ae593309/org.fcitx.Fcitx5.Addon.Rime.yaml#L118

But the `default.yaml` from rime-prelude did not activite them.
https://github.com/rime/rime-prelude/blob/3803f09458072e03b9ed396692ce7e1d35c88c95/default.yaml#L6-L15

WORKROUND:
add a `default.custom.yaml` in Rime user data dir: `~/.var/app/org.fcitx.Fcitx5/data/fcitx5/rime/default.custom.yaml`
with content like this:
```yaml
patch:
  schema_list:
    - schema: luna_pinyin
    - schema: luna_pinyin_simp
    - schema: luna_pinyin_fluency
    - schema: bopomofo
    - schema: bopomofo_tw
    - schema: cangjie5
    - schema: stroke
    - schema: terra_pinyin
    - schema: double_pinyin
```

It's my first time use Rime, I waste 5 hours on how to activite doube-pinyin...and finally found flatpak already installed
same schema.yaml. then find out how Rime works.

I new to flatpak too. So I can't make a PR fix this in `org.fcitx.Fcitx5.Addon.Rime.yaml`.
